# Site settings
title: Danny Peters
email: danmanstx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings of a Computer Science / Computer Engineering graduate turned
  Web Developer. Lover of Kentucky Basketball, Ruby, and Beer.
  Looking for where the web meets the bare metal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dannypeters.me" # the base hostname & protocol for your site
twitter_username: danmanstx
github_username:  danmanstx

gems: ["emoji_for_jekyll"]
# Build settings
markdown: kramdown
